### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by nguyenngoctongan** [bastisk/leaflet-search-types#2]
Hi, I appreciate your solution, but would it be possible that you publish this to npm?

**Comment by benf35** [comment]
Hi, got the same need please :) 

Thanks

**Comment by devaskim** [comment]
Me too

**Comment by tandyx** [comment]
Hi all, 

I don't know if this is still applicable to you all two years later, but I modified bastisk's definitions and published them to npm
https://github.com/johan-cho/leaflet-search-types

**Comment by bastisk** [comment]
Thanks all for your interest in me publishing it. As you all noticed I didn't find the time to publish the definitions to npm. As @johan-cho did this now, I think it is time to archive this repository. 

I added a link in the readme to the repo of @johan-cho, so anybody looking for this will find his work.

Thanks guys!
